name: Compile FFmpeg with Vorbis codec (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install MSYS2
        run: choco install msys2

      - name: Initialize MSYS2 and install dependencies
        run: |
          C:\tools\msys64\usr\bin\bash.exe -c "pacman -Syu --noconfirm"
          C:\tools\msys64\usr\bin\bash.exe -c "pacman -S --noconfirm git yasm nasm make mingw-w64-x86_64-vorbis"

      - name: Clone FFmpeg repository
        run: git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git ffmpeg

      - name: Configure FFmpeg with only Vorbis
        run: |
          cd ffmpeg
          C:\tools\msys64\usr\bin\bash.exe -c "./configure --enable-libvorbis --disable-everything --enable-ffplay --enable-vorbis --disable-encoders --disable-decoders --disable-hwaccels"

      - name: Build FFmpeg
        run: |
          cd ffmpeg
          C:\tools\msys64\usr\bin\bash.exe -c "make -j$(nproc)"

      - name: Install FFmpeg
        run: |
          cd ffmpeg
          C:\tools\msys64\usr\bin\bash.exe -c "make install"

      - name: Upload FFmpeg Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-vorbis-build
          path: ffmpeg
